[package]
name = "mysqld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql_parser = {path= "../sql_parser"}
tokio = { version = "1.0", features = ["full"] }
chumsky = {version = "0.9.3"}